name: iucn-red-list
recipe: laravel

config:
  webroot: public
  php: '8.4'
  via: nginx
  database: mariadb:11.4
  xdebug: true

proxy:
  phpmyadmin:
    - phpmyadmin.iucn-red-list.lndo.site

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_24.x | bash -
      - apt-get update -y
      - apt-get install -y nodejs
      - npm install -g yarn
    build:
      - yarn
    ssl: true
    ports:
      - '24695:24695'
      - '24696:24696'
      - '24697:24697'

tooling:
  pint:
    service: appserver
    cmd: ./vendor/bin/pint
  test:
    service: appserver
    cmd: ./vendor/bin/phpunit
  tinker:
    service: appserver
    cmd: php artisan tinker
  artisan:
    service: appserver
    cmd: php artisan
  node:
    service: appserver
  yarn:
    service: appserver

  dev:
    service: appserver
    description: Start vite dev server
    user: root
    cmd: yarn dev
